name: CoreUtility
authors: [Hepolite]
main: com.hepolite.coreutility.PluginCoreUtility
version: 0.0.1
depend: [EffectLib, PermissionsEx]
description: >
             The core plugin for most other plugins, provides quite a lot of useful functionality

commands:
    cu:
        description: Core command for Core Utility. Use /cu help for more info
        usage: /cu <arguments>
        permission: coreutility.cu
        permission-message: Sorry, you don't have permission to use this command
permissions:
    coreutility.cu:
        description: Gives access to the Core Utility commands